before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database grandham_test;'
  - RAILS_ENV=test bundle exec rake db:migrate test

notifications:
  email:
    - ershad92@gmail.com